Added my profile markup
cValentyna/myAndroidProject pull request #1
Opened 2024-08-01 20:58 UTC by cValentyna

Added my profile markup. I tried to send my first level by smaller parts. This is first part.  
I just noticed that something wrong with my fontWeight.

2024-08-04 12:05 UTC, 1937Carrie requested changes

2024-08-12 19:38 UTC, cValentyna commented on app/src/main/res/drawable/full_fb.xml
connected ellips with logo

2024-08-12 19:40 UTC, cValentyna commented on app/src/main/res/font/open_sans_semibold.ttf
added one more type of font

2024-08-12 19:41 UTC, cValentyna commented on app/src/main/res/layout-land/activity_main.xml
added landscape orientation (changed only image size)

2024-08-12 19:45 UTC, cValentyna commented on app/src/main/res/layout/activity_main.xml
>  <androidx.constraintlayout.widget.ConstraintLayout xmlns:android="http://schemas.android.com/apk/res/android"
returned constraint layout

2024-08-12 19:46 UTC, cValentyna commented on app/src/main/res/layout/activity_main.xml
> +    <View
added view for blue part

2024-08-12 19:48 UTC, cValentyna commented on app/src/main/res/layout/activity_main.xml
> +    <androidx.appcompat.widget.AppCompatTextView
changed types of views from simple to appcompat

2024-08-12 19:53 UTC, cValentyna commented on app/src/main/res/layout/activity_main.xml
> +    <com.google.android.material.imageview.ShapeableImageView
removed default size of image. cardview was changed to ShapeableImageView

2024-08-12 19:57 UTC, cValentyna commented on app/src/main/res/layout/activity_main.xml
> +        app:layout_constraintVertical_bias="@dimen/bias_vertical_social_network_frame" />
imageButtos were changet to ImageView.

2024-08-12 20:00 UTC, cValentyna commented on app/src/main/res/layout/activity_main.xml
> +        android:src="@drawable/full_fb"
Elipses and logos are together

2024-08-12 20:07 UTC, cValentyna commented on app/src/main/res/values-v26/styles.xml
added fontWeight for v26

2024-08-12 20:10 UTC, cValentyna commented on app/src/main/res/values-v28/styles.xml
Added styles for different weights when 28 and higher api is used. Unfortunately it does not work when dimension is used.

2024-08-12 20:10 UTC, cValentyna commented on app/src/main/res/values/dimens.xml
renamed names and added needed values

2024-08-12 20:13 UTC, cValentyna commented on app/src/main/res/values/styles.xml
> +<!-- style for image frame   -->
style for image shape

2024-08-12 21:11 UTC, 1937Carrie approved these changes
Correct margin of text profession to the top and to the bottom and go on.

2024-08-24 09:09 UTC, EugeneOrlov204 approved these changes

2024-08-30 14:37 UTC, merged