added auth activity
cValentyna/myAndroidProject pull request #10
Opened 2024-08-30 16:27 UTC by cValentyna

Added auth activity and little connection with main activity. Also added error messages without validation.

2024-08-30 19:35 UTC, Khar-Ma2 requested changes
#### Code
short and simple, but it is definitely necessary to prescribe validation for the fields, and add a check for errors on the "register" button
#### Xml layout
I just looked at it.
Subjective opinion: you are relying too much on v\h_Bias and percentage widths/heights. 
So instead, **where possible**, it's good to use padding/margins, bindings to other components and wrap_content sizes (or if it's height, you can use a specific size in dp if necessary)

2024-08-30 19:35 UTC, Khar-Ma2 commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +        }
Are you sure that an error should be displayed whenever there is something(isNotEmpty) in the field?

2024-08-30 19:35 UTC, Khar-Ma2 commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +        }
Are you sure that an error should be displayed whenever there is something(isNotEmpty) in the field?

Are you sure that an error should be displayed every time there is something in the field?

For email validation, I recommend using the regex pattern
https://developer.android.com/reference/android/util/Patterns

General about regex in kotlin 
https://betulnecanli.medium.com/regular-expressions-regex-in-kotlin-a2eaeb2cd113

2024-08-30 19:40 UTC, Khar-Ma2 commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +}
add a check for the validity of the e-mail and password before performing the transition

2024-08-31 11:56 UTC, cValentyna commented on app/src/main/res/layout-land/activity_auth.xml
done. I corrected touched sizes for all of needed elements inside landscape layout

2024-08-31 13:04 UTC, cValentyna commented on app/src/main/res/layout/activity_auth.xml
checbox Touch target size was changed. 
About buttonAuthGoogle I tried to follow figma design for screen like 5inch where this button height = 40px. But I can change it.

2024-09-01 18:17 UTC, Khar-Ma2 approved these changes

2024-09-04 11:01 UTC, kogorbach commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +        binding.textInputEditTextAuthPassword.doOnTextChanged { text: CharSequence?, _, _, _ ->
consider little more decomposition in onCreate() e.g. 
onCreate {
    super()
    setClickListeners()
    setTextChangedListeners()
}

2024-09-04 11:03 UTC, kogorbach commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +                if (text.isNotEmpty()) {
you can use nullOrEmpty() to prevent nested ifs

2024-09-04 11:06 UTC, kogorbach commented on app/src/main/java/com/project/myapp/MainActivity.kt
> +        ViewCompat.setOnApplyWindowInsetsListener(binding.activityMain) { v, insets ->
same call as in another activity, might want to consider extracting it as a util function, delegate, or use base activity

2024-09-06 10:06 UTC, cValentyna commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +        binding.textInputEditTextAuthPassword.doOnTextChanged { text: CharSequence?, _, _, _ ->
I'm not sure that I did as you wanted. But I moved everything to separate methods, which were moved outside.

2024-09-06 10:06 UTC, cValentyna commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +                if (text.isNotEmpty()) {
it was corrected

2024-09-06 10:06 UTC, cValentyna commented on app/src/main/java/com/project/myapp/MainActivity.kt
> +        ViewCompat.setOnApplyWindowInsetsListener(binding.activityMain) { v, insets ->
I have deleted it for now. In the future, I want to learn more  about util function.

2024-09-06 12:14 UTC, kogorbach approved these changes

2024-09-10 19:47 UTC, merged