added email-password validation and navigation from auth to main (with data passing)
cValentyna/myAndroidProject pull request #11
Opened 2024-09-12 09:44 UTC by cValentyna

Added email-password validation:
errors are shown if user pressed registration button or tried to fill textfield but lost focus before correct information was filled in.

Added navigation from auth to main (with data passing), also animation was added between activities

2024-09-12 11:15 UTC, 1937Carrie requested changes

2024-09-12 11:15 UTC, 1937Carrie commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +            email.substring(0, email.indexOf('@')).replace("[._]".toRegex(), " ").lowercase()
```kotlin
val partOfEmail = email.substringBefore("@").split(".", "_").joinToString(" ")
```

2024-09-12 11:15 UTC, 1937Carrie commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +        val pattern = Regex("^[\\w-.]+@([\\w-]+\\.)+\\w{2,}\$")
Built-in email address pattern matcher `Patterns.EMAIL_ADDRESS`.
```kotlin
Patterns.EMAIL_ADDRESS.matcher(text.toString()).matches() // check if the email pattern matches the given text
```

2024-09-12 11:15 UTC, 1937Carrie commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +    private var firstFocusPassword = false
This is looks like properties for holding UI state. If you want to hold it check out this [topic](https://developer.android.com/topic/architecture/ui-layer). If this turns out to be difficult, contact on discord and you will get help.

2024-09-17 17:12 UTC, cValentyna commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +            email.substring(0, email.indexOf('@')).replace("[._]".toRegex(), " ").lowercase()
It was fixed.

2024-09-17 17:13 UTC, cValentyna commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +        val pattern = Regex("^[\\w-.]+@([\\w-]+\\.)+\\w{2,}\$")
Also it was changed.

2024-09-17 17:31 UTC, cValentyna commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +    private var firstFocusPassword = false
Unfortunately I couldn't figure it out myself.

2024-09-20 08:18 UTC, cValentyna commented on app/src/main/java/com/project/myapp/AuthActivity.kt
> +    private var firstFocusPassword = false
Done.

2024-09-20 10:33 UTC, 1937Carrie approved these changes
Overall, it was done very well. If you will need help with providing improves to the project - let me know in discord. What else can be improved:

1. You hold email and password validators right in activity class. Activity belongs to the UI layer, text validators belong to the data layer. Validators can be extracted outside activity class and be calling in viewmodel for passing gotten result of validation to activity;
2. I see you left some comments above classes, functions. There is exists some different type of comments, [source](https://kotlinlang.org/docs/basic-syntax.html#comments):
```kotlin
// This is an end-of-line comment

/* This is a block comment
   on multiple lines. */

/* The comment starts here
/* contains a nested comment */
and ends here. */

// Below is KDoc's comment
/**
 * A group of *members*.
 *
 * This class has no useful logic; it's just a documentation example.
 *
 * @param T the type of a member in this group.
 * @property name the name of this group.
 * @constructor Creates an empty group.
 */
class Group<T>(val name: String) {
    /**
     * Adds a [member] to this group.
     * @return the new size of the group.
     */
    fun add(member: T): Int { ... }
}
```
3. About string resources. It is not necessary, but you can manually group string, like you are doing now, and then sort comments belong to some group, e.g. select needed lines -> Edit -> Sort lines
<img width="397" alt="image" src="https://github.com/user-attachments/assets/929822b1-1771-4f10-9eb1-eb860b565602">

2024-11-16 15:21 UTC, EugeneOrlov204 requested changes

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +}
It's a business logic, should be part of the ViewModel

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                .isNotEmpty()
why do you need to check edit texts when you already have a authState in the viewmodel?

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +            ) {
Invalid formatting. I suggest you setup the Ktlint: https://pinterest.github.io/ktlint/latest/. We use ktlint in our production product and while having a team of approximately 15 android devs it helps us to maintain good code quality.

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                }
This looks like a business logic thus shouldn't be on UI layer.

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +            }
same as below

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +            }
This is definitely a business logic. Please separate from UI.

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +     */
I advise you to use [Kdoc](https://kotlinlang.org/docs/kotlin-doc.html#block-tags) for better comments. Also, some tools can convert your Kdocs to a nice looking documentation.

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                if (isEmailAndPasswordCorrect()) {
it's odd to see that you validate email and password and then check their validity. I would rather have some link this:
```suggestion
                if (isEmailValid() && isPasswordValid()) {
```

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                if (isEmailAndPasswordCorrect()) {
Also, it makes sense to keep in setOnClickListener just setting listeners and move all the click events to separate functions.

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +)
Please read about single responsibility. This is a violation of this principle: Auth state keeps track of the following:  
- Email validity
- Password validity
- Several different focuses (which I suspect might be a focus of EditText which should be part of the UI, not the EditText)
- Register button clickable state

Usually, you would create an enum or a sealed class to keep track of your authorization status, such as SUCCESS, INVALID_EMAIL, INVALID_PASSWORD, NETWORK_ERROR etc. But this requires some time to think and create scalable and reusable architecture.

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +}
I am happy to see that you aware about ViewModels and use them, but please try to separate UI from business logic as was suggested in comments above.

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/main/MainActivity.kt
> +        getName()
"get" suggests that this method should return a value:
![image](https://github.com/user-attachments/assets/df93a15a-04f8-473a-ae15-5089d4fd5b14)
https://en.wikibooks.org/wiki/Object_Oriented_Programming/Getters_and_Setters

2024-11-16 15:21 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/main/MainActivity.kt
> +                startActivity(intent, option.toBundle())
move this logic to a separate function

2024-11-19 14:58 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                    Toast
I'd create an extension funcion on Context for making toasts, you can check our 'ext' channel in discord for this and other extensions

2024-11-19 15:16 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +}
I think this is actually a valid approach tbh

2024-11-19 15:29 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                    intent.putExtra("userName", userName)
hardcoded key string is dangerous for typos, better store them in a separate file or object

2024-11-19 15:39 UTC, YevheniiOrlovIntellias commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +}
Please look at the AuthState implementation. I agree that in general this view model looks ok, but the way it is used is not

2024-11-19 15:46 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                if (hasFocus) {
kudos for doing the focus change stuff

2024-11-19 15:47 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                } else if (!v.isFocused && viewModel.authState.value.firstFocusPassword) {
normally you wouldn't access values of viewmodels flows/states/liveData from UI layer, I'd suggest reviewing if you can move this logic to the viewmodel

2024-11-19 15:54 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +    private fun validateEmail(text: CharSequence?) {
consider doing the validation process in a viewmodel or a custom validator class, you can return the R.string id from there and apply it in the activity. Hope it makes sense, feel free to reach out for clarifications

2024-11-19 15:59 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +        val patternLetterLC = Regex("(?=.*[a-z])")
could be just me, but it's not too obvious that LC and UC are lower casae and upper case, also I'm not a big fan of regex so I'd probably avoid them completely. I will text you an example how I managed some text validations recently, just to share ideas

2024-11-19 16:06 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +    private fun isEmailAndPasswordCorrect(): Boolean =
Having 'and' in function's name sugggests doing several operations in it, which we probably always want to avoid

2024-11-19 16:08 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +)
agreed, I think MVI principles would have a guideline on this approach, @EugeneOrlov204 can you confirm?

2024-11-19 16:09 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/main/MainActivity.kt
> +    }
hardcoded string key, mentioned earlier, just pinging it here as well to notice

2024-11-19 16:13 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    fun updateState(reducer: AuthState.() -> AuthState) {
I had to look up what this AuthState.() was, apparently this is caled extension function receiver, and looks to me like a very high level thing, great job!

2024-11-19 16:14 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +}
Yeah the implementation is questionable, agree here, but overall having a UI state in viewmodel doesn't seem to be a bad or uncommon practice

2024-11-22 07:35 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                .isNotEmpty()
I needed it because if editText was empty it was considered as correct input data. An it wasn't processed in authState. I will fix it.

2024-11-22 07:36 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +            ) {
I've already use Ktlint. I will try to correct it

2024-11-22 07:37 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    fun updateState(reducer: AuthState.() -> AuthState) {
It is Stanislav's idea and suggestion, because I tried to listen to focuses and other authStates without viewModel and a separated class.

2024-12-01 18:39 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +}
It was moved to the [viewModel](https://github.com/cValentyna/myAndroidProject/pull/11/commits/424fa1694f60903a312870565eb0d4f02883cfe7#:~:text=*/-,fun%20getName(email%3A%20String)%3A%20String%20%3D,%7B%20it%20%2D%3E%20it.lowercase().replaceFirstChar%7B%20it.uppercaseChar()%20%7D%20%7D,-companion%20object%20%7B)

2024-12-01 18:39 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                }
I moved direct call from authState to viewModel [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/424fa1694f60903a312870565eb0d4f02883cfe7#:~:text=%7D-,fun%20focusEmailUpdate(,%7D,-private%20fun%20getString)
and validate logic [here] (https://github.com/cValentyna/myAndroidProject/pull/11/commits/424fa1694f60903a312870565eb0d4f02883cfe7#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3bR75:~:text=%3E().getString(int)-,fun%20validatePassword(text%3A%20CharSequence)%3A%20String%3F%20%7B,%7D,-/**)

2024-12-01 18:40 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +            }
I moved it to [AuthViewModel](https://github.com/cValentyna/myAndroidProject/pull/11/commits/424fa1694f60903a312870565eb0d4f02883cfe7#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3b)

2024-12-01 18:40 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                if (isEmailAndPasswordCorrect()) {
I moved this logic to separated functions [ba705ab](https://github.com/cValentyna/myAndroidProject/pull/11/commits/ba705abf1603225de65a864cf10707dff8327df4), but after next movements it was a little bit changed in [424fa16](https://github.com/cValentyna/myAndroidProject/pull/11/commits/424fa1694f60903a312870565eb0d4f02883cfe7)

2024-12-01 18:40 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/main/MainActivity.kt
> +        getName()
It was fixed [0e586d4cbf390426ae6c5878f4f7109c691f94aa](https://github.com/cValentyna/myAndroidProject/pull/11/commits/0e586d4cbf390426ae6c5878f4f7109c691f94aa)

2024-12-01 18:41 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/main/MainActivity.kt
> +                startActivity(intent, option.toBundle())
It was changed [0e586d4cbf390426ae6c5878f4f7109c691f94aa](https://github.com/cValentyna/myAndroidProject/pull/11/commits/0e586d4cbf390426ae6c5878f4f7109c691f94aa)

2024-12-01 18:41 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                    Toast
I added [extensionFunction](https://github.com/cValentyna/myAndroidProject/pull/11/commits/ba705abf1603225de65a864cf10707dff8327df4#diff-ba28775a683a4f8a67bff9a9aa7044df9cdb907bb4cb560227644fd76b17521b)

2024-12-01 18:41 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                    intent.putExtra("userName", userName)
I changed it.

2024-12-01 18:41 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                } else if (!v.isFocused && viewModel.authState.value.firstFocusPassword) {
I moved validation and direct call authState to [viewModel](https://github.com/cValentyna/myAndroidProject/pull/11/commits/424fa1694f60903a312870565eb0d4f02883cfe7#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3b)

2024-12-01 18:41 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +    private fun validateEmail(text: CharSequence?) {
Validation was moved to [viewModel](https://github.com/cValentyna/myAndroidProject/pull/11/commits/424fa1694f60903a312870565eb0d4f02883cfe7#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3b)

2024-12-01 18:41 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +        val patternLetterLC = Regex("(?=.*[a-z])")
It was changed [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/424fa1694f60903a312870565eb0d4f02883cfe7#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3bR75:~:text=fun%20validatePassword(text%3A%20CharSequence)%3A,return%20null)   
But i didn't follow your example.

2024-12-01 18:42 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/main/MainActivity.kt
> +    }
It was changed [0e586d4cbf390426ae6c5878f4f7109c691f94aa](https://github.com/cValentyna/myAndroidProject/pull/11/commits/0e586d4cbf390426ae6c5878f4f7109c691f94aa)

2024-12-01 18:45 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                }
I moved direct call from authState and validate logic to [viewModel ](https://github.com/cValentyna/myAndroidProject/pull/11/commits/424fa1694f60903a312870565eb0d4f02883cfe7#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3b)

2024-12-02 10:05 UTC, kogorbach commented on app/src/main/java/com/project/myapp/ExFunctions.kt
> +object ExtensionUtils {
you don't need an object to create extension functions, it is usually a plain file
e.g.
<img width="958" alt="image" src="https://github.com/user-attachments/assets/7e60ebce-23d0-418e-a0e4-f63a9085b6a4">

2024-12-02 10:32 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    private fun getString(int: Int): String = getApplication<Application>().getString(int)
you shouldn't access context and resources in a viewmodel, better to return the resource id instead, and then access it from activity or fragment

2024-12-03 18:03 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    private fun getString(int: Int): String = getApplication<Application>().getString(int)
I changed [it](https://github.com/cValentyna/myAndroidProject/pull/11/commits/372427c33fa5983eb0e53a1c5f21c53fb2bcc8d3#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3b).
I hope that's what you meant.

2024-12-03 18:03 UTC, cValentyna commented on app/src/main/java/com/project/myapp/ExFunctions.kt
> +object ExtensionUtils {
It was [changed ](https://github.com/cValentyna/myAndroidProject/pull/11/commits/372427c33fa5983eb0e53a1c5f21c53fb2bcc8d3#diff-ba28775a683a4f8a67bff9a9aa7044df9cdb907bb4cb560227644fd76b17521b)

2024-12-04 09:57 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    private fun getString(int: Int): String = getApplication<Application>().getString(int)
yes, beautifuly done, you might want to also annotate return type of those functions with @StringRes so it's more clear that it's not just an Int

2025-02-20 17:31 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +)
I tried to change [AuthState class](https://github.com/cValentyna/myAndroidProject/pull/11/commits/984ad6ae893840e1ca29a5c223a7b002e4004efd?diff=split&w=0) as sealed class, therefore [viewModel](https://github.com/cValentyna/myAndroidProject/pull/11/commits/fc6731b6ab19ef4edce4de56cd758e621cf0f9f8) was changed, and observers were added in [AuthActivity](https://github.com/cValentyna/myAndroidProject/pull/11/commits/c06bd793abf380069d740aa5dcd640d619394f32?diff=split&w=0#).

2025-02-21 09:52 UTC, kogorbach commented on app/src/main/java/com/project/myapp/ExFunctions.kt
> +    fun AppCompatActivity.toast(message: String) {
imo, an extension on Context would be more flexible as you would be able to call from activities, fragments, dialogs, etc

2025-02-21 09:57 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                when (state) {
loving this, it's important to keep exhaustive when blocks, like this one, not to forget to adjust those if a new Enum/sealed class value is introduced

2025-02-21 09:57 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                    this.toast(state.message?.let { getString(it) }.toString())
i think it can work without 'this.'

2025-02-21 10:04 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +        data object InvisibleError : PasswordState()
In my humble opinion, it's better to not store any resources in these classes at all but rather to have a separate state for each possible error and then, based on the error state, display appropriate text message

2025-02-21 10:04 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +        }
To me it looks like code duplication

2025-02-21 10:05 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +        finish()
also, you can do something like:
Intent().apply {
putExtra() 
doAdditionalActionOnTheObject()
}

2025-02-21 10:07 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +        if (!pattern && email.isNotEmpty()){
I haven't done this myself on my pet projects, but consider setting up a GitHub CI with a linter on it. I think it would be a good point during interviews

2025-02-21 10:07 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +        if (!pattern && email.isNotEmpty()){
I haven't done this myself on my pet projects, but consider setting up a GitHub CI with a linter on it. I think it would be a good point during interviews

2025-02-21 10:07 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
ViewModel should not be aware of string resources like this.

2025-02-21 10:08 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
Your auth validation logic has grown to be complex, consider moving it to a separate class. It would be ideal if you set up a DI framework and inject that class using it.

2025-02-21 10:09 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +        val pattern = Patterns.EMAIL_ADDRESS.matcher(email).matches()
doesn't that pattern cover isEmpty case?

2025-02-21 10:09 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +
for now it's ok but I would move it to another class/object

2025-02-21 10:10 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
I think methods validatePassword and validateEmail should have validated for the empty field case thus I don't see a point for having an additional method like this.

2025-02-21 10:10 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
why not? it's not accessing it, only returning the resource id. The question remains though is that this method doesn't do anything, could just as well call the respective string resource directly instead of calling the viewmodel method

2025-02-21 10:14 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
"Email error" in my opinion is too vague of a description. It can be anything from empty email, invalid email to email that already exists errors that I would rather rely on enums and assign appropriate text on the UI side. Also, this solution would be beneficial since you could share the state across multiple screens which would react differently to the same error message (but in this particular case it's unlikely)

2025-02-21 10:14 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +        val userName = viewModel.getName(binding.textInputEditTextAuthEmail.text.toString())
it's not that critical, but 'get' sounds to me like fetching from a data source like network API, what we do in viewmodel sounds more like parsing

2025-02-21 10:18 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +        val option =
it looks to me like an animation, why option?

2025-02-21 10:21 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +        data class Error(val message: Int?) : EmailState()
should message be nullable here and in the rest of error states?

2025-02-21 10:26 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    val credentialsState: LiveData<AuthState> get() = _credentialsState
not a mistake, just a recommendation to try out flow, I've seen much more flows than live datas recently, would be useful

2025-02-21 10:30 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    val credentialsState: LiveData<AuthState> get() = _credentialsState
LiveData is a rare bird these days :)

2025-02-21 10:43 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +                    !password.validSigns() ||
the same methods are called in getError(), so you could call it right away, and rely on it returning null to determine valid password

2025-02-21 10:44 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +            text.onlyLetters() ->
ghwfeio@#@
not only letters, still missing a digit, similar cases for other checks

2025-02-21 10:57 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/main/MainActivity.kt
> +    }
nice, please resolve here

2025-02-21 11:00 UTC, kogorbach commented on app/src/main/java/com/project/myapp/ExFunctions.kt
> +    fun AppCompatActivity.toast(message: String) {
also a more popular approach would be to have an 'ext' or 'extension' folder, and then separate files for each class you create an extension for, in this case, it would be ext.Activity, or ext.Context, if you change to context extension

2025-02-21 11:02 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +            text.onlyLetters() ->
oh, you seem to forbid special characters here, if that's the case, you can resolve and ignore this comment, my bad

2025-02-21 11:06 UTC, kogorbach requested changes
changes requested, overall comment: you are overdoing comments, variables and namings are generally very descriptive and precise, that is enough to understand what your code does. Don't comment on **what** it does, comment **why** it does so, if needed of course. One case where I would keep the comment is your workaround with invisible error where you pause validation

2025-02-25 17:14 UTC, cValentyna commented on app/src/main/java/com/project/myapp/ExFunctions.kt
> +    fun AppCompatActivity.toast(message: String) {
It was changed [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/31992ff1e7f14b2cc1c68649897dee36e23ebd7b)

2025-02-25 17:14 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +                    this.toast(state.message?.let { getString(it) }.toString())
corrected it

2025-02-25 17:14 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +        data object InvisibleError : PasswordState()
I changed it [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/76d257965af4c89ba8b9a712dbaa9afced8bfd79?diff=split&w=0#diff-ff6b82efc6079a290f10a2da121531c0d479abdcf6b2ac9e57b8500eb7c78e49)

2025-02-25 17:15 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +        finish()
It was changed [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/8601c9565859f01af4e04b211da5cb3b53cc559d#diff-003477427236e4babf86151628b05bb3917f7fdd61b2351b73d6b5631e5d588a:~:text=val%20userName%20%3D%20viewModel.parseName,startActivity(intent%2C%20animation.toBundle()))

2025-02-25 17:16 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
I changed this and the same methods [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/76d257965af4c89ba8b9a712dbaa9afced8bfd79?diff=split&w=0#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3bR27-R39). And thereform [activity](https://github.com/cValentyna/myAndroidProject/pull/11/commits/76d257965af4c89ba8b9a712dbaa9afced8bfd79?diff=split&w=0#diff-003477427236e4babf86151628b05bb3917f7fdd61b2351b73d6b5631e5d588a) was changed.

2025-02-25 17:16 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
these methods were removed and their functions was moved [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/76d257965af4c89ba8b9a712dbaa9afced8bfd79?diff=split&w=0#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3bR27-R39) and for password - below

2025-02-25 17:16 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +        val userName = viewModel.getName(binding.textInputEditTextAuthEmail.text.toString())
it was changed

2025-02-25 17:17 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
> +        val option =
I think because ActivityOptionsCompat is used here. I found an example of implementing this animation and used it.. I changed the name.

2025-02-25 17:17 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +        data class Error(val message: Int?) : EmailState()
It could be needed in previous variant of code because my validation functions could return null in cases when checked data was emty(now empty data processes together with other validation). but I changed [AuthState](https://github.com/cValentyna/myAndroidProject/pull/11/commits/76d257965af4c89ba8b9a712dbaa9afced8bfd79?diff=split&w=0#diff-ff6b82efc6079a290f10a2da121531c0d479abdcf6b2ac9e57b8500eb7c78e49) class and Error() does not receive message now.

2025-02-25 17:17 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    val credentialsState: LiveData<AuthState> get() = _credentialsState
changes to flow are [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/87658ae873dcdb3282cde086ef092f0885d3892d)

2025-02-25 17:17 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +                    !password.validSigns() ||
these methods were removed and their functions was moved [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/76d257965af4c89ba8b9a712dbaa9afced8bfd79?diff=split&w=0#diff-2295a611bb9936b9489b1011294a72134f5f861ce9134628200a0eb81359af3bR27-R39) for email and for password - below

2025-02-25 17:18 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
I tried to do it with "koin". And it even works, but I'm not sure I understand all of it. I`ve not pusshed these changes.

2025-02-25 19:29 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/main/MainActivity.kt
> +                startActivity(intent, option.toBundle())
@EugeneOrlov204 please approve for resolve so we can clean up conversation a bit

2025-02-25 19:32 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
LGTM here

2025-02-25 19:33 UTC, kogorbach commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +    }
Using a DI is a junior level, understanding it is a strong middle level or higher, it's fine, as long as you see the pattern in your head and can duplicate injections, also wouldn't be a bad idea to check Hilt

2025-02-26 06:05 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +)
> agreed, I think MVI principles would have a guideline on this approach, @EugeneOrlov204 can you confirm?

Not sure I understand what you are saying...

2025-02-26 06:11 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/main/MainActivity.kt
> +                startActivity(intent, option.toBundle())
@kogorbach I am not sure how to do so, it seems that either I am stupid or don't have rights for that :)

2025-02-26 06:12 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
>                          -> null
why not `else -> null`?

2025-02-26 06:14 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +     * which depends on filled data
Comment should not be obvious and duplicate what is written in code. Usually, you would comment the parts of the code that are hard to understand without additional explanations.

2025-03-01 11:07 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthActivity.kt
>                          -> null
when I added new states, this view was clearer to me. You are right, your solution is better. It was changed [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/1960d2a943f4056ef58550c3ade1c82e7125da08#diff-003477427236e4babf86151628b05bb3917f7fdd61b2351b73d6b5631e5d588a).

2025-03-01 11:07 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +     * which depends on filled data
It was a little bit changed [here](https://github.com/cValentyna/myAndroidProject/pull/11/commits/1960d2a943f4056ef58550c3ade1c82e7125da08)

2025-03-01 13:57 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> + */
redundant comment

2025-03-01 13:58 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +        data object Initial : EmailState()
Maybe, you could make EmailState extend the AuthState and use the latter's Initial state? I mean, you structured the code as if it would be an inheritance but it does not look like it

2025-03-01 14:00 UTC, EugeneOrlov204 commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +        }
what do you think about this?
```suggestion
      _emailState.value = if (email.isEmpty()) {
             AuthState.EmailState.ErrorEmpty
        } else if (!pattern) {
             AuthState.EmailState.Error
        } else {
             AuthState.EmailState.Valid
        }
```

2025-03-01 16:36 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> + */
Comment was removed.

2025-03-01 16:36 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthViewModel.kt
> +        }
Your solution is definitely better and clearer. I changed [it](https://github.com/cValentyna/myAndroidProject/pull/11/commits/08ab598199580641ae3d9cca49db7081f02819a0)

2025-03-01 16:37 UTC, cValentyna commented on app/src/main/java/com/project/myapp/screens/auth/AuthState.kt
> +        data object Initial : EmailState()
EmailState and PasswordState [was extended](https://github.com/cValentyna/myAndroidProject/pull/11/commits/73cede8bf68e30a6647bd53b47bc91a1908b2514) AuthState, but this part :

>  use the latter's Initial state

wasn't clear to me. EmailState and PasswordState changes separately and AuthState depends on both (that`s why EmailState and PasswordState are located inside AuthState).

2025-03-01 17:32 UTC, EugeneOrlov204 approved these changes

2025-03-02 17:43 UTC, merged